import { ICar } from "@/utils";

export const cars: ICar[] = [
  {
    city_mpg: 25,
    class: "Compact",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.0,
    drive: "FWD",
    fuel_type: "Gasoline",
    highway_mpg: 33,
    make: "Honda",
    model: "Civic",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.5,
    drive: "AWD",
    fuel_type: "Gasoline",
    highway_mpg: 27,
    make: "Toyota",
    model: "Highlander",
    transmission: "Automatic",
    year: 2022,
  },
  {
    city_mpg: 15,
    class: "Pickup",
    combination_mpg: 17,
    cylinders: 8,
    displacement: 5.0,
    drive: "RWD",
    fuel_type: "Gasoline",
    highway_mpg: 20,
    make: "Ford",
    model: "F-150",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 30,
    class: "Sedan",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 1.8,
    drive: "FWD",
    fuel_type: "Gasoline",
    highway_mpg: 36,
    make: "Toyota",
    model: "Corolla",
    transmission: "CVT",
    year: 2021,
  },
  {
    city_mpg: 52,
    class: "Hatchback",
    combination_mpg: 50,
    cylinders: 4,
    displacement: 1.5,
    drive: "FWD",
    fuel_type: "Hybrid",
    highway_mpg: 48,
    make: "Hyundai",
    model: "Ioniq",
    transmission: "Automatic",
    year: 2022,
  },
  {
    city_mpg: 18,
    class: "Luxury",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 3.0,
    drive: "AWD",
    fuel_type: "Gasoline",
    highway_mpg: 26,
    make: "BMW",
    model: "530i",
    transmission: "Automatic",
    year: 2023,
  },
  {
    city_mpg: 24,
    class: "Crossover",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.4,
    drive: "AWD",
    fuel_type: "Gasoline",
    highway_mpg: 30,
    make: "Subaru",
    model: "Forester",
    transmission: "CVT",
    year: 2022,
  },
  {
    city_mpg: 22,
    class: "SUV",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "AWD",
    fuel_type: "Gasoline",
    highway_mpg: 27,
    make: "Mazda",
    model: "CX-5",
    transmission: "Automatic",
    year: 2023,
  },
  {
    city_mpg: 120,
    class: "Sedan",
    combination_mpg: 120,
    cylinders: 0,
    displacement: 0.0,
    drive: "AWD",
    fuel_type: "Electric",
    highway_mpg: 112,
    make: "Tesla",
    model: "Model 3",
    transmission: "Automatic",
    year: 2024,
  },
  {
    city_mpg: 50,
    class: "Hybrid",
    combination_mpg: 52,
    cylinders: 4,
    displacement: 1.8,
    drive: "FWD",
    fuel_type: "Hybrid",
    highway_mpg: 48,
    make: "Toyota",
    model: "Prius",
    transmission: "CVT",
    year: 2021,
  },
  {
    city_mpg: 19,
    class: "SUV",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 3.6,
    drive: "AWD",
    fuel_type: "Gasoline",
    highway_mpg: 25,
    make: "Chevrolet",
    model: "Traverse",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 23,
    class: "Sedan",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.0,
    drive: "FWD",
    fuel_type: "Gasoline",
    highway_mpg: 31,
    make: "Nissan",
    model: "Altima",
    transmission: "CVT",
    year: 2021,
  },
  {
    city_mpg: 44,
    class: "Hatchback",
    combination_mpg: 46,
    cylinders: 4,
    displacement: 1.6,
    drive: "FWD",
    fuel_type: "Hybrid",
    highway_mpg: 48,
    make: "Kia",
    model: "Niro",
    transmission: "Automatic",
    year: 2023,
  },
  {
    city_mpg: 13,
    class: "Luxury",
    combination_mpg: 15,
    cylinders: 12,
    displacement: 6.0,
    drive: "RWD",
    fuel_type: "Gasoline",
    highway_mpg: 18,
    make: "Rolls-Royce",
    model: "Phantom",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 17,
    class: "Sports",
    combination_mpg: 20,
    cylinders: 8,
    displacement: 5.2,
    drive: "RWD",
    fuel_type: "Gasoline",
    highway_mpg: 25,
    make: "Chevrolet",
    model: "Corvette",
    transmission: "Manual",
    year: 2022,
  },
  {
    city_mpg: 29,
    class: "Compact",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 1.5,
    drive: "FWD",
    fuel_type: "Gasoline",
    highway_mpg: 36,
    make: "Ford",
    model: "Focus",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 21,
    class: "SUV",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.5,
    drive: "AWD",
    fuel_type: "Gasoline",
    highway_mpg: 29,
    make: "Honda",
    model: "CR-V",
    transmission: "CVT",
    year: 2022,
  },
  {
    city_mpg: 110,
    class: "Sedan",
    combination_mpg: 115,
    cylinders: 0,
    displacement: 0.0,
    drive: "RWD",
    fuel_type: "Electric",
    highway_mpg: 120,
    make: "Lucid",
    model: "Air",
    transmission: "Automatic",
    year: 2024,
  },
  {
    city_mpg: 40,
    class: "Hatchback",
    combination_mpg: 42,
    cylinders: 4,
    displacement: 1.4,
    drive: "FWD",
    fuel_type: "Gasoline",
    highway_mpg: 45,
    make: "Volkswagen",
    model: "Golf",
    transmission: "Manual",
    year: 2021,
  },
  {
    city_mpg: 24,
    class: "Minivan",
    combination_mpg: 26,
    cylinders: 6,
    displacement: 3.6,
    drive: "FWD",
    fuel_type: "Gasoline",
    highway_mpg: 28,
    make: "Chrysler",
    model: "Pacifica",
    transmission: "Automatic",
    year: 2022,
  },
];
